version: '3.8'

services:
  osmand-tracker:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - tracker-network

  # Optionnel: Nginx comme reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - osmand-tracker
    restart: unless-stopped
    networks:
      - tracker-network

networks:
  tracker-network:
    driver: bridge
